apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: k8s-ldaps-compose-zip
  namespace: openldap
spec:
  secretName: k8s-ldaps-docker-compose-zip-tls
  issuerRef:
    name: vault-clusterissuer
    kind: ClusterIssuer
  duration: 2160h # 90j
  renewBefore: 360h # 15j
  commonName: k8s-ldaps.docker-compose.zip
  dnsNames:
  - k8s-ldaps.docker-compose.zip
  - openldap-0.openldap-headless.openldap.svc.k8s-demo-01.local
  - openldap-1.openldap-headless.openldap.svc.k8s-demo-01.local
  - openldap-2.openldap-headless.openldap.svc.k8s-demo-01.local