apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: k8s-ss-password-docker-compose-zip
  namespace: openldap
spec:
  secretName: k8s-ss-password-docker-compose-zip-tls
  issuerRef:
    name: vault-clusterissuer
    kind: ClusterIssuer
  duration: 2160h # 90j
  renewBefore: 360h # 15j
  commonName: k8s-ss-password.docker-compose.zip
  dnsNames:
  - k8s-ss-password.docker-compose.zip